# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmyDQxpxjoGtTcYn2iCj9PpgbPY3Gd90
"""



filename=str(input("Input the Filename:"))
extension = filename.split('.')[-1]
print("The extension of the file is", extension)