# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JRwsA16U2gapXEn9rkOWMp8-apEUPLpD
"""

'''
write a python progam that iterates the intergers from 1 to 50. For multiples of three print
"Fizz" instead of the number and for multiples of five print "Buzz".
For numbers that are multiples of three and five, print "FizzBuzz".
'''

for i in range (1,50):
  if i%3==0 and i%5==0:
    print("FizzBuzz")

  elif i%3==0:
    print("Fizz")

  elif i%5==0:
    print("Buzz")

  else:
    print(i)