# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_1OgFuJdIx163lsGVpF5U0NibFAQdkC
"""

'''
write a python code to create a function called most_frequent that takes a
string and prints the letters in a decreasing order of freqency.use dictionaries

'''

def most_frequent():
  word = input("enter a word ")
  letter_count = {}

  for letter in word:
    letter_count[letter] = letter_count.get(letter, 0) + 1
    sort_dict=dict(sorted(letter_count.items(),key=lambda item: item[1], reverse=True))
  return(sort_dict)

most_frequent()