# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JRwsA16U2gapXEn9rkOWMp8-apEUPLpD
"""

'''
write a python program to guess a number between 1 and 9. Note: User is prompted to enter a guess.
If the user guesses wrong then the prompt appears again until the guess is correct, on a successful guess,
user will get a "Well Guessed!" message, and the program will exit.
'''
print("Let's start the Game")
x=input("Enter your Guess")

for i in range(1,10):
  while x !=5:
    print("wrong, re-try")
    x=int(input("Enter your guess"))

if x==5:
  print("Well Guessed!")