# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPVxoMGiTkqeykOjiW_OYWOC0LmFrJw7
"""

import random

def ai_guess_number(low, high):
    return random.randint(low, high)

def main():
    print("Welcome to the Number Guessing Game!")
    print("I have chosen a random number between 1 and 100 (inclusive).")
    print("You have 7 attempts to guess the number.")

    low, high = 1, 100
    user_number = random.randint(low, high)
    attempts = 0

    while attempts < 7:
        attempts += 1
        guess = int(input(f"Attempt {attempts}: Enter your guess: "))

        if guess == user_number:
            print(f"Congratulations! You guessed the number {user_number} correctly in {attempts} attempts!")
            break
        elif guess < user_number:
            print("Your guess is too low! Try again.")
        else:
            print("Your guess is too high! Try again.")

    else:
        print(f"Game over! The number was {user_number}. Better luck next time!")

if __name__ == "__main__":
    main()