# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXy6Z7hlhy8vPIf9UqeMKtl89uc5ZO5K
"""

list1=[12,-7,5,64,-14]
print("input list1",list1)
positive_numbers=[]
for num in list1:
  if num > 0:
    positive_numbers.append(num)
print("output",positive_numbers)

list2=[12,14,-95,3]
print("input list2",list2)
positive_number=[]
for number in list2:
  if number > 0:
    positive_number.append(number)
print("output",positive_number)