# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxrnRPDGXxbDQItP_8AfLhSiwI7x64fw
"""

import requests
from bs4 import BeautifulSoup
import pandas

hotel_url="https://www.parkregisbusinessbay.com/"
page_num_MAX=3

for page_num in range(1,page_num_MAX):
  req=requests.get(hotel_url+str(page_num))
  content=req.content

  soup=BeautifulSoup(content,"html.parser")

  all_hotels=soup.find_all("div",{"class": "hotelCardlisting"})
  scraped_info_list=[]

  for hotel in all_hotels:
   hotel_dict={}
   hotel_dict["name"]=hotel.find("h3",{"class":"listingHotelDescriptoion_hotelName"}).text
   hotel_dict["address"]=hotel.find("span",{"intemprop":"streetAdress"}).text
   hotel_dict["price"]=hotel.find("span",{"class":"listingPrice_finalPrice"}).text

   try:
       hotel_dict["rating"]=hotel.find("span",{"class": "hotelRating_ratingSummary"}).text
   except AttributeError:
       pass

   parent_amenities_element=hotel.find("div",{"class": "amenityWrapper"})

   amenities_list=[]
   for amenity in parent_amenities_element.find_all("div",{"class": "amenityWrapper_amenity"}):
    amenities_list.append(amenity.find("span", {"class": "d-body-sm"}).text.strip())

    hotel_dict["amenities"]=', '.join(amenities_list[::-1])
    scraped_info_list.append(hotel_dict)

def scrape_books():
    url = 'https://www.parkregisbusinessbay.com/'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    books = []
    for book_element in soup.find_all('div', class_='book'):
        title = book_element.find('h2').text
        author = book_element.find('p', class_='author').text
        genre = book_element.find('p', class_='genre').text
        books.append((title, author, genre))

    return books